spring.application.name=Intellecta Backend
server.port=8080

# This line tells Spring to "Include" the settings from application-dev.properties
spring.profiles.active=dev

# SHARED DATABASE SETTINGS
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# File upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# SHARED SECURITY/JWT
# Generate a strong key: openssl rand -base64 64
jwt.secret=St4iDJ0aM/FZqlBAnB8VfLYefFJ1LD2KdoK4OtyEnao2y73Mub2377AQ3Xi6x0rtJ1LvicFvjqPItJCAb4+zdg==
jwt.expiration=86400000
