spring.application.name=Intellecta Backend
server.port=8080

# This line tells Spring to "Include" the settings from application-dev.properties
spring.profiles.active=dev

# SHARED DATABASE SETTINGS
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# File upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# SHARED SECURITY/JWT
jwt.secret=intellecta_super_secret_key_2026
jwt.expiration=86400000
spring.security.user.name=admin
spring.security.user.password=password123